const DarkTheme = {
  PRIMARY_BACKGROUND: '#070417',
  // SECONDARY_BACKGROUND: "#111827",
  SECONDARY_BACKGROUND: '#162334',
  HEADER_BACKGROUND: '#070417',
  OPPOSITE_PRIMARY_BACKGROUND: '#E5E7EB',
  PRIMARY_TEXT: '#FFFFFF',
  SECONDARY_TEXT: '#828282',
  DANGER_BTN_COLOR: '#DC2626',
  INFO_BTN_COLOR: '#1D4ED8',
  SECTION_TITLE_BACKGROUND: '#e04352',
  ACTIVE_ICON_COLOR: 'white',
  INACTIVE_ICON_COLOR: '#868687',
  OPPOSITE_COLOR_PRIMARY_TEXT: '#fff',
  OPPOSITE_COLOR_SECONDARY_TEXT: '#e3e4e8',
};

const LightTheme = {
  PRIMARY_BACKGROUND: '#fff',
  SECONDARY_BACKGROUND: '#e3e4e8',
  HEADER_BACKGROUND: '#fff',
  OPPOSITE_PRIMARY_BACKGROUND: '#070417',
  PRIMARY_TEXT: '#000001',
  SECONDARY_TEXT: '#4E6294',
  DANGER_BTN_COLOR: '#DC2626',
  INFO_BTN_COLOR: '#1D4ED8',
  SECTION_TITLE_BACKGROUND: '#e04352',
  ACTIVE_ICON_COLOR: '#e04352',
  INACTIVE_ICON_COLOR: '#dddee2',
  OPPOSITE_COLOR_PRIMARY_TEXT: '#fff',
  OPPOSITE_COLOR_SECONDARY_TEXT: '#e3e4e8',
};

export {DarkTheme, LightTheme};
